/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Papeleria;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class Main extends javax.swing.JFrame {
     DefaultTableModel modelo = new DefaultTableModel();
       ArrayList<Producto> listaProductos;
       AgregarDatos aD = new AgregarDatos();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setModelo();
    }
    private void setModelo(){
        String[] cabecera = {"Id", "Nombre", "Descripcion", "Piezas", "Precio Unitario",};
        modelo.setColumnIdentifiers(cabecera);
        arteTbl.setModel(modelo);
        
    }
    private void leerlista(){
        try{
            ObjectInputStream leyendoFichero = new ObjectInputStream(
                    new FileInputStream("data/Productos.obj") );
//            Producto objProductoLeido = (Producto) objInput.readObject();
            listaProductos = (ArrayList <Producto>) leyendoFichero.readObject();
            leyendoFichero.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    private void setDatos(){
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for(Producto theprod:listaProductos){
            datos[0] = theprod.getIdProducto();
            datos[1] = theprod.getNombreDelProducto();
            datos[2] = theprod.getDescripcion();
            datos[3] = theprod.getCantidad();
            datos[4] = theprod.getPrecioUnitario();
            modelo.addRow(datos);
        }
        arteTbl.setModel(modelo);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        artePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arteTbl = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();
        agregarDatosPanel = new javax.swing.JPanel();
        verProductosBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        arteBtn = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arteTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(arteTbl);

        agregarBtn.setText("AgregarProducto");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarDatosPanelLayout = new javax.swing.GroupLayout(agregarDatosPanel);
        agregarDatosPanel.setLayout(agregarDatosPanelLayout);
        agregarDatosPanelLayout.setHorizontalGroup(
            agregarDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        agregarDatosPanelLayout.setVerticalGroup(
            agregarDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        verProductosBtn.setText("Ver Productos");
        verProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout artePanelLayout = new javax.swing.GroupLayout(artePanel);
        artePanel.setLayout(artePanelLayout);
        artePanelLayout.setHorizontalGroup(
            artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregarDatosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(artePanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(verProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        artePanelLayout.setVerticalGroup(
            artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(artePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarBtn)
                            .addComponent(verProductosBtn))))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jMenu1.setText("Catalogos");

        arteBtn.setText("Arte");
        arteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arteBtnActionPerformed(evt);
            }
        });
        jMenu1.add(arteBtn);

        jMenuItem3.setText("Papeles");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Escritura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setText("Regalos");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Adeshivos");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Generales");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(artePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(artePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arteBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:
        
        agregarDatosPanel.add(aD);
        aD.show();
           
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void verProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductosBtnActionPerformed
        leerlista();
        setDatos();
        artePanel.repaint();


    }//GEN-LAST:event_verProductosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JPanel agregarDatosPanel;
    private javax.swing.JMenuItem arteBtn;
    private javax.swing.JPanel artePanel;
    private javax.swing.JTable arteTbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton verProductosBtn;
    // End of variables declaration//GEN-END:variables
}
